### ISSUE TITLE
Error: Unable to resolve module 'events'

### ISSUE THREAD

**Issue by QuanTumli** [maxdeviant/redux-persist-transform-encrypt#10]
I'm getting an error if I try to import this module into a ```React Native```app.
I installed the ```redux-persist-transform-encrypt```with
```shell
npm i --save redux-persist-transform-encrypt
```

Then i try to import the module as follows:
```javascript
import createEncryptor from 'redux-persist-transform-encrypt'
```

This will give me the following error:
```
Unable to resolve module events from /redux-persist-transform-encrypt/node_modules/readable-stream/lib/_stream_readable.js
```

Any ideas what the problem could be?

**Comment by maxdeviant** [comment]
@QuanTumli What version of the library are you using?

**Comment by QuanTumli** [comment]
Here are the **dependencies** from my `package.json`:

```javascript
"dependencies": {
    "react": "15.4.1",
    "react-native": "^0.39.2",
    "react-redux": "^5.0.1",
    "redux": "^3.6.0",
    "redux-persist": "^4.0.1",
    "redux-persist-transform-encrypt": "^0.2.0"
  }
```

**Comment by maxdeviant** [comment]
@QuanTumli Looks like the problem is that React Native doesn't have access to the native Node module [`events`](https://nodejs.org/api/events.html).

It's a dependency stemming from `readable-stream`, which is only needed for the async encryptor.

The `v0.2.0` release is a bit messy, so my plan is to cut another release soon, where the sync and async encryptors are behind separate exports, so my hope is React Native will be able to ignore the problematic dependency.

**Comment by maxdeviant** [comment]
@QuanTumli Would you mind trying this out with `v1.0.0` and see if it fixes your issue?

**Comment by QuanTumli** [comment]
@maxdeviant Thanks, the error with the module `events` is gone now.
But now there's a new error, I've opened another bug #12 and will close this one.
