### ISSUE TITLE
Securing the secret key

### ISSUE THREAD

**Issue by tybro0103** [maxdeviant/redux-persist-transform-encrypt#16]
Question: Any tips on what to use as a secret key that would be secure?

Being this is normally going to be client code, using a hard-coded string as the key would be rather insecure, as anyone gaining access to the data would probably also extract strings from the app binary.

Perhaps using something like an MD5 of the device ID could be ok.

Any recommendations?

**Comment by maxdeviant** [comment]
@tybro0103 This sort of depends on how you want the persisted data to work.

If you're only interested in persisting over the course of a single session, then something like an access token or a session key would be good candidates for the secret key.

If you want the data to be persisted long-term, then a hash of the device ID might work. I would say that if you go with that approach, you probably want to salt the device ID with some secret on the server or in native code to make it harder to crack.

If you have any sort of server or API that you're interacting with, you could have it deterministically generate a secure string for the user that you would then pass back to the client.

Funnily enough, we didn't get far enough to use this library in production, since we switched from Redux to MobX, so I've never actually solved this problem :smile:

**Comment by tybro0103** [comment]
Whatever the salt is would have to be stored somewhere... 🙃

**Comment by maxdeviant** [comment]
@tybro0103 Ah yes, I was implying that the hashing/salting would be done on a server somewhere, where the key could be secret.

**Comment by rubencodes** [comment]
Either way the string would be passed back to the client... So that wouldn't be super ideal either... I think in an ideal universe we'd pass the state to a server-side function which would do the hashing/encryption, then pass it back to the frontend. Same for unencrypting.

**Comment by maxdeviant** [comment]
@rubencodes Passing the state back and forth just seems like a lot of overhead. If you're using unique encryption keys for each user and sending them to the client for decryption, that is just as secure as doing what you described and decrypting the state on the server, but much more efficient.

But this all really comes down to what your encryption needs are for your application. Which is something that I cannot prescribe for you :smile:

The only thing I definitely advise against is using a single secret key for the entire application, as this is pretty insecure since it's leaked to the client.

**Comment by rubencodes** [comment]
Good call!

**Comment by MNF** [comment]
Suggestions what can be used as deviceId see at https://stackoverflow.com/questions/49692073/how-can-i-get-a-unique-device-id-in-javascript/49692307#49692307
