### ISSUE TITLE
Is the package supported  in react-web?

### ISSUE THREAD

**Issue by MNF** [maxdeviant/redux-persist-transform-encrypt#37]
In readme there is no information, does is the package supported in react-web, or only in react-native?
There is only examples/ReactNativeExample.	

Lack of answer to @pitops question https://github.com/maxdeviant/redux-persist-transform-encrypt/issues/28#issuecomment-468172488_ makes think that there is no way to keep secretkey in JavaScript in browser, that will not be visible to potential hackers.
Am I wrong?

**Comment by maxdeviant** [comment]
@MNF It should be supported in both. The reason there is only a React Native example is because there have been a number of people having trouble with getting it to work with React Native.

In #16 I go into some potential solutions for keeping keys somewhat secret in the browser, but there are no 100% perfect solutions. It really all depends on the level of security that you need for your application.

**Comment by MNF** [comment]
Created PR https://github.com/maxdeviant/redux-persist-transform-encrypt/pull/38 to update readme
