### ISSUE TITLE
How to use .env.local variables with next js13 app directory

### ISSUE THREAD

**Issue by thanogod** [maxdeviant/redux-persist-transform-encrypt#72]
This is my code:
import { combineReducers } from 'redux'
import { persistReducer } from 'redux-persist'
import storage from 'redux-persist/lib/storage'
import moneyReducer from './Features/moneySlice'
import podReducer from './Features/PrintonDemand/podSlice'
import profileReducer from './Features/PrintonDemand/profileSlice'
import ButtonReducer from './Features/Buttons/ButtonsSlice'
import { encryptTransform } from 'redux-persist-transform-encrypt';
import SeasonsSlice from './Features/Seasons/SeasonsSlice'

const rootPersistConfig = {
  
    key: 'persist-key',
    storage: storage, 
    transforms:[
        encryptTransform({
          secretKey: process.env.KEY,
          onError: function (error :Error) {
            // Handle the error.
          },
        }),
      ],
   
  }
 

const rootReducer = combineReducers({
    
    flag: podReducer,
    profile: profileReducer,
    money:moneyReducer,
    Buttons:ButtonReducer,
    Seasons: SeasonsSlice,
    
    
})
export default persistReducer(rootPersistConfig, rootReducer),
.env.local: KEY='key'

and it shows this error:Error: redux-persist-transform-encrypt: No secret key provided.:

**Comment by maxdeviant** [comment]
Is your `redux-persist` code running on the server or the client?

If it's on the client then the reason the secret key is not available is because it needs to be exposed as `NEXT_PUBLIC_KEY` in order to be visible to the client. See the [Next.js environment variable docs](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser) for more details.

However, I don't think exposing it as `NEXT_PUBLIC_KEY` is a safe solution here, as it means the secret key would be visible to the client, and if you're using a shared secret key for all users (which would be the case if it's set as a global environment variable), then it defeats the point of encrypting the store, as anyone would have the key to decrypt it.

What I would suggest is returning a user-specific secret key to the client as part of the sign-in process and then using that to encrypt/decrypt the user's store.

**Comment by thanogod** [comment]
ty so much,you are a legend.
